### ISSUE TITLE
Chrome doesn't seem to be starting on Travis-CI

### ISSUE THREAD

**Issue by zombie** [webdriverio-community/wdio-chromedriver-service#11]
Just forking this on github and enabling Travis-CI errors out with:

    ERROR: unknown error: Chrome failed to start: crashed

I have a small project that uses wdio-chromedriver-service, and travis tests stopped working a few weeks ago.

**Comment by zombie** [comment]
Here is an example log from travis:
https://travis-ci.org/zombie/wdio-chromedriver-service/builds/345775878

**Comment by mohsen1** [comment]
read up this
