### ISSUE TITLE
Feature - Luncher Timeout from options

### ISSUE THREAD

**Issue by m4hdyar** [webdriverio-community/wdio-chromedriver-service#192]
Hi,

Now there is a `POLL_TIMEOUT` in luncher.js. The timeout amount is hardcoded to 10 Seconds. But when you use something like
 [ Electron Service ](https://github.com/webdriverio-community/wdio-electron-service) and Electron it can be possible that it takes more than 10 seconds. Specially when you run everything in debugging mode. 
So I suggest adding timeout to options.

If you think it makes sense I can create a pull request for it.

Thanks.

**Comment by christian-bromann** [comment]
> If you think it makes sense I can create a pull request for it.

Totally make sense, any PR would be appreciated.

**Comment by m4hdyar** [comment]
> > If you think it makes sense I can create a pull request for it.
> 
> Totally make sense, any PR would be appreciated.

Thanks for the answer. PR is there #193. Im not sure if adding POLL_INTERVAL to options makes also sense because I can't see any usecase to customize this Interval. So just added pollTimeout

**Comment by christian-bromann** [comment]
This can be closed now as the proposed change has been implemented and released.
