### ISSUE TITLE
Unhandled Request Error

### ISSUE THREAD

**Issue by lcharbon** [webdriverio-community/wdio-chromedriver-service#20]
webdriverio will not connect to chrome driver unless `spawn` is changed to `exec` in chromedriver library [here](https://github.com/giggio/node-chromedriver/blob/5d01633458b5f72c9cbb8f346c60b112c8d5dd87/lib/chromedriver.js#L28).

Node: v10.15.3
chromedriver: 74.0.3729.6
chrome:  74.0.3729.108 
macOS: 10.14.4

**Comment by christian-bromann** [comment]
WebdriverIO can connect perfectly fine using `spawn`. What would be the reason for your assumption?
