### ISSUE TITLE
Remove @wdio/cli as a peerDependency

### ISSUE THREAD

**Issue by DylanPiercey** [webdriverio-community/wdio-chromedriver-service#22]
With support for wdio@5 a [peerDependency of the cli](https://github.com/atti187/wdio-chromedriver-service/blob/master/package.json#L36) was added to this module. That means that people who are using wdio via the programatic api now need to install the cli to use this plugin for no reason.

**Comment by atti187** [comment]
It came from https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-selenium-standalone-service and I didn't think much about it... Are you suggesting to remove that line altogether?

**Comment by DylanPiercey** [comment]
It should be perfectly fine to remove. As I said it is possible to use WebdriverIO without the cli, maybe slightly less common? Either way this module only depends on the `webdriverio` base module not the CLI.

You can see some docs on using wdio without the cli here: https://webdriver.io/docs/multiremote.html#using-standalone-mode

**Comment by christian-bromann** [comment]
@DylanPiercey if you use WebdriverIO in standalone mode I recommend to use the `chromedriver` NPM package directly. There is no reason why you would use this service. It is designed to be used with `@wdio/cli`.
