### ISSUE TITLE
Headless remote debugging

### ISSUE THREAD

**Issue by albertogasparin** [webdriverio-community/wdio-chromedriver-service#4]
I've tried to set the `--remote-debugging-port` arg to easily debug headless Chrome, but it looks like tests are not run with that option (without it they run just fine).

Config:
```js
  // ...
  capabilities: [
    {
      browserName: 'chrome',
      maxInstances: 3,
      chromeOptions: {
        args: [
          '--headless',
          '--disable-gpu',
          '--window-size=1280,750',
          '--remote-debugging-port=9222',
        ],
        binary: '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary',
      },
    },
  ],
  port: '9515',
  path: '/',
  services: ['chromedriver'],
  // ...
```

I'm using: wdio@4.8.0, wdio-chromedriver-service@0.1.0 and Chrome Canary 61.0.3153.0 (earlier versions have issues on OSX).
Do you know how see/interact with Chrome headless, combining webdriverio `browser.debug()`?

**Comment by atti187** [comment]
Sorry, been away for a while and missed this. And no, haven't looked into it...

**Comment by christian-bromann** [comment]
This should be possible with latest Chromedriver and Chrome. Please let me know if it isn't and I can re-open.
