### ISSUE TITLE
Move project to WebdriverIO Community Org

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-chromedriver-service#49]
Hey @atti187,

first off, thank you for creating this plugin and extending the WebdriverIO ecosystem!

I was wondering if you would be interested moving this repository into the [WebdriverIO Community](https://github.com/webdriverio-community) organisation. It would allow us to help maintain this package, automate a few things like releases and allow others to contribute to it and make the package even better. You would of course continue to have full access to it.

What do you think? Please let me know if you have any questions.

**Comment by atti187** [comment]
Hi, I've had this discussion with @erwinheitzman a while ago (and yourself in the very beginning), so you might want to check with him for the full history. We had an  e-mail conversation about it, but TL;DR; - I'm ok with it as long as I can still track my contribution.

**Comment by christian-bromann** [comment]
> I'm ok with it as long as I can still track my contribution.

Absolutely. If we transfer this repo through GitHub all history stays intact. You will get an org invite so you will have access to not only your own repository but also all others. The reasoning behind is that we as a ecosystem want to make sure we can continue develop services and reporters even without having the core maintainer to be the person who has to always merge and release the code (bus factor).

**Comment by christian-bromann** [comment]
If you are ok with that, please follow [this guide](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#transferring-a-repository-owned-by-your-user-account) and put `webdriverio-community` as new owner of this repository. We will then invite you to the org to regain you access to the code.

**Comment by atti187** [comment]
Done! Please verify...

**Comment by christian-bromann** [comment]
Perfect, thank you!
