### ISSUE TITLE
Add `wdio-user` to list of NPM maintainer

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-chromedriver-service#55]
Hey @atti187 ,

could you add [`wdio-user`](https://www.npmjs.com/~wdio-user) to be an NPM package maintainer?

Thanks!

**Comment by atti187** [comment]
wdio-user is invited...

**Comment by christian-bromann** [comment]
Thanks, was able to release through GitHub Action pipeline.
