### ISSUE TITLE
Is it possible to have a single instance?

### ISSUE THREAD

**Issue by mlynch** [webdriverio-community/wdio-chromedriver-service#65]
I'm noticing this spawns a new Chrome window for each spec. Is it possible to configure the number of processes used for a test. In particular, is it possible to have a single instance and run each test serially?

**Comment by christian-bromann** [comment]
@mlynch WebdriverIO is designed to run every spec file in a separated session and therefor in in a new browser instance. If you set `maxInstances` to 1 all test will run sequentially.

**Comment by mlynch** [comment]
@christian-bromann thanks, with that I'm able to get them to run sequentially but a new Chrome instance is created for each spec. Is it possible to stay in a single instance? Trying to replicate the experience of running in a simulator with Appium where there is only a single app instance running through each spec

**Comment by christian-bromann** [comment]
> Is it possible to stay in a single instance?

Yes you can group your specs, see https://webdriver.io/docs/organizingsuites#grouping-test-specs-to-run-sequentially

I will close this as it is not really related to the Chromedriver service, happy to continue to help though!

**Comment by mlynch** [comment]
Ah yes! That was the difference and why it wasn’t working in my new test app. Thanks for the help
