### ISSUE TITLE
7.3.0 Spawns Chromedriver process and then times out waiting for port to free up.

### ISSUE THREAD

**Issue by canderson-activatecare** [webdriverio-community/wdio-chromedriver-service#74]
Didn't see an issue template here, but when working with our testing partner. The upgrade to 7.3.0 started making all of our tests fail with the newly introduced error.

https://github.com/webdriverio-community/wdio-chromedriver-service/pull/73

Was the 'waitUntilFree' supposed to be executed prior to the launch of the child process?  Perhaps even wrapping it?  Instead it appears to run directly after chromedriver is launched and times out reporting that the port is in use.  This occurred in an environment that runs many agents.

**Comment by christian-bromann** [comment]
Thanks for reporting.

Apologise for this stupid mistake. I pushed a fix and released it as `v7.3.1`.
