### ISSUE TITLE
Chromedriver error

### ISSUE THREAD

**Issue by Nith-j** [webdriverio-community/wdio-chromedriver-service#77]
Getting selenium.common.exceptions.WebDriverException: Message: invalid argument: unrecognized capability: chromeOptions

Getting the above error message while running a project

**Comment by christian-bromann** [comment]
`chromeOptions` is invalid, you should use `goog: chromeOptions`, see also the [docs](https://chromedriver.chromium.org/capabilities#h.p_ID_106).
