### ISSUE TITLE
Assisted upgrade of fs-extra available

### ISSUE THREAD

**Issue by jsfix-updater** [webdriverio-community/wdio-chromedriver-service#79]
Version 10 of fs-extra is available.
  The JSFIX tool can help you through the update process (**Ensuring that all the necessary changes are made to your project in the process**).
  Use this [link](https://jsfix.live/jsfix/https%3A%2F%2Fgithub.com%2Fwebdriverio-community%2Fwdio-chromedriver-service) to start the upgrade process (_It's completely free_).
  
  Leave a comment on this issue if you have any questions or concerns.

**Comment by christian-bromann** [comment]
@jsfix-updater I have not opted into this. This project can just use dependabot. Please don't spam random projects to advertise for some random service.
