### ISSUE TITLE
Downloading Chromedriver fails due to `self signed certificate in certificate chain`

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-chromedriver-service#82]
I am not entirely sure if this is an issue caused by this package or a server problem.

**Comment by apreg** [comment]
This was more of an issue with self-signed certificates but you can see the solution in the related ticket. Additional information is I'm using Netskope which interferes with local certificates a bit. See more here https://docs.netskope.com/en/configuring-cli-based-tools-and-development-frameworks-to-work-with-netskope-ssl-interception.html

**Comment by christian-bromann** [comment]
Ah! This is an information I wasn't aware of. In this case I will close this as it seems to be a configuration issue. If there is anything this service can do to make the integration better, let us know.
